#!/bin/bash

if [ $# -ne 1 ]; then
   echo "$0: Usage: $0 directoryName"
   exit 2
fi

directory=$1

if [ ! -d $directory ]; then
   echo "$0: $directory does not exist or is not a directory?"
fi

files=`find $directory -name "*.htm*" | xargs egrep '(|background="/|calendar|FAQ|href="|input|Login|src="/|pubs/search/|wiki)' | awk -F: '{print $1}' | sort | uniq`

#files=`find $directory -type f | xargs egrep 'Quick search by ...' | awk -F: '{print $1}' | sort | uniq`

#files=`find $directory -type f | xargs egrep 'FAQ sections' | awk -F: '{print $1}' | sort | uniq`

#files=`find . -type f | xargs egrep 'referer=%2Fpubs%2F' | awk -F: '{print $1}' | sort | uniq`

echo "Found `echo $files | wc -w` files that may need fixing"

tmp=/tmp/fixweb.$$

for file in $files
do
	echo $file

	# sed \
	#     -e "s@link rel=\"stylesheet\" href=\"/@link rel=\"stylesheet\" href=\"/projects/$directory/@g" \
        #     -e "s@<a href=\"/@<a href=\"/projects/$directory/@g" \
	#     -e "s@link href=\"/@link href=\"/projects/$directory/@g" \
	#     -e "s@src=\"/@<a src=\"/projects/$directory/@g" \
        #     -e "s@background=\"/@background=\"/projects/$directory/@g" \
 	#     -e "s@link href=\"/styles@link href=\"/projects/$directory/styles@g" \
 	#     -e "s@src=\"/img@src=\"/projects/$directory/img@g" \
	#     -e 's@<li class="first"><a href="/[^"]*login/">Login</a></li>@@' \
	#     $file > $tmp


	    # -e 's@pubs/search/?groupname=\([^&]*\)&amp;Action=Search@pubs/search/\1.html@' \
	    # -e 's@<li><a href="/[^"]*/calendar">Calendar</a> </li>@@' \

	    # -e 's@<input type="hidden" name="cx" value="[^"]*" />@<input type="hidden" name="cx" value="007295758319438328285:skvr4laywa4" />@' \
	    # -e 's@<li><a href="[^"]*">FAQ</a></li>@@' \
	    # -e "s@/projects/$directory/projects/$directory@/projects/$directory@g" \
	    # -e 's@/projects/terraswarm/login/?denied=1&amp;referer=%2Fpubs%2F\([0-9]*\).html@https://wiki.eecs.berkeley.edu/terraswarm-urbanheartbeat/Main/Publications#Publication_\1@' \
	    # -e 's@<a href="/[^"]*/login/">Login</a>@@' \

	# grep -ve '  <h2 class="sectionhead">Quick search by ...</h2>    <h3 class="sectionhead">Year</h3>' \
	#    -ve '<li><a href="/projects/cps-forces/pubs/search/.*</li>' \
	#    -ve '<h3 class="sectionhead">Group</h3>' \

	#grep -ve '<h2 class="sectionhead">FAQ sections</h2>' \
        #     -ve '<li><a href="/projects/cps-forces/forces/faq.*</li>' \
	#    $file > $tmp

	# -e 's@pubs/search/?year=\([0-9]*\)&amp;Action=Search@pubs/search/\1.html@' \
	sed 's@href="http[s]*://robotics.eecs.berkeley.edu@href="/projects/robotics@g' \
		$file > $tmp
	diff $file $tmp
	cp $tmp $file
done